/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc380;
import java.sql.*;
import javax.swing.JOptionPane;
public class adminFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminFrame
     */
    public adminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        addText = new javax.swing.JPanel();
        fName = new javax.swing.JLabel();
        LName = new javax.swing.JLabel();
        phoneNumText = new javax.swing.JTextField();
        LNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fNameText = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        chooseP = new javax.swing.JRadioButton();
        chooseD = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        adminIDText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        specialtyText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        DOSText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        depText = new javax.swing.JTextField();
        IDText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fileNumText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DOBText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        genderText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        allergyText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        searchFileNumText = new javax.swing.JTextField();
        searchPatient = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchPatientText = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        searchDocIDText = new javax.swing.JTextField();
        searchDoc = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchDocText = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        upcomingApp2 = new javax.swing.JButton();
        allPatient2 = new javax.swing.JButton();
        allDoc2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        viewText2 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addText.setBorder(javax.swing.BorderFactory.createTitledBorder("Add"));
        addText.setToolTipText("");
        addText.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fName.setText("First Name");
        addText.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        LName.setText("Last Name");
        addText.add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 84, 25));

        phoneNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumTextActionPerformed(evt);
            }
        });
        addText.add(phoneNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, -1));

        LNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameTextActionPerformed(evt);
            }
        });
        addText.add(LNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 160, -1));

        jLabel5.setText("phone no.");
        addText.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 68, 16));

        fNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTextActionPerformed(evt);
            }
        });
        addText.add(fNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 56, 150, 20));

        add.setText("Add Patient");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        addText.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        addText.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        add1.setText("Add Doctor");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        addText.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        buttonGroup1.add(chooseP);
        chooseP.setText("Patient");
        chooseP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePActionPerformed(evt);
            }
        });
        addText.add(chooseP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        buttonGroup1.add(chooseD);
        chooseD.setText("Doctor");
        chooseD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDActionPerformed(evt);
            }
        });
        addText.add(chooseD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setText("Admin ID");
        addText.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        adminIDText.setText("   ");
        addText.add(adminIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 105, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Doctor"));
        jPanel1.setEnabled(false);

        jLabel10.setText("Specialty");

        specialtyText.setEnabled(false);
        specialtyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialtyTextActionPerformed(evt);
            }
        });

        jLabel11.setText("Date of Start");

        DOSText.setEnabled(false);
        DOSText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOSTextActionPerformed(evt);
            }
        });

        jLabel12.setText("Email");

        emailText.setEnabled(false);

        jLabel13.setText("Department no.");

        depText.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DOSText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(specialtyText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specialtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(DOSText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        addText.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 260, 190));
        addText.add(IDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 160, 19));

        jLabel4.setText("National ID");
        addText.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient"));
        jPanel2.setEnabled(false);

        fileNumText.setEnabled(false);
        fileNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNumTextActionPerformed(evt);
            }
        });

        jLabel6.setText("File number:");

        jLabel7.setText("Date of Birth:");

        DOBText.setEnabled(false);
        DOBText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTextActionPerformed(evt);
            }
        });

        jLabel8.setText("Gender:");

        genderText.setEnabled(false);

        jLabel9.setText("Allergies:");

        allergyText.setEnabled(false);
        allergyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergyTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DOBText, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(fileNumText))
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allergyText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DOBText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        addText.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Patient"));

        searchFileNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFileNumTextActionPerformed(evt);
            }
        });

        searchPatient.setText("Search");
        searchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPatientActionPerformed(evt);
            }
        });

        jLabel14.setText("File no.");

        searchPatientText.setColumns(20);
        searchPatientText.setRows(5);
        jScrollPane1.setViewportView(searchPatientText);

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchFileNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(searchPatient)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(searchFileNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Doctor"));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        searchDocIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDocIDTextActionPerformed(evt);
            }
        });

        searchDoc.setText("Search");
        searchDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDocActionPerformed(evt);
            }
        });

        jLabel15.setText("ID");

        searchDocText.setColumns(20);
        searchDocText.setRows(5);
        jScrollPane2.setViewportView(searchDocText);

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchDocIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(searchDoc)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(searchDocIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("View "));

        upcomingApp2.setText("Upcoming Appointments");
        upcomingApp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upcomingApp2ActionPerformed(evt);
            }
        });

        allPatient2.setText("All Patients");

        allDoc2.setText("All Doctors");
        allDoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allDoc2ActionPerformed(evt);
            }
        });

        viewText2.setColumns(20);
        viewText2.setRows(5);
        jScrollPane5.setViewportView(viewText2);

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton6))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(upcomingApp2)
                                .addGap(57, 57, 57)
                                .addComponent(allPatient2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allDoc2))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upcomingApp2)
                    .addComponent(allPatient2)
                    .addComponent(allDoc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addText, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addText, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumTextActionPerformed

    private void LNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameTextActionPerformed

    private void specialtyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialtyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialtyTextActionPerformed

    private void fNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTextActionPerformed

    private void fileNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNumTextActionPerformed

    private void DOSTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOSTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOSTextActionPerformed

    private void DOBTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTextActionPerformed

    private void allergyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergyTextActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic_management", "root", "Ghala_439202867");
            String sql = "insert into patient values(?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            int fileNo = Integer.parseInt(fileNumText.getText());
            pstmt.setInt(1, fileNo);
            
            pstmt.setString(2,fNameText.getText());
            pstmt.setString(3,LNameText.getText());
            pstmt.setString(4,phoneNumText.getText());
            pstmt.setString(5,genderText.getText());

            long millis= System.currentTimeMillis();
            java.sql.Date date = new java.sql.Date(millis);
            date.valueOf(DOBText.getText());
            pstmt.setDate(6, date);

            int id = Integer.parseInt(IDText.getText());
            pstmt.setInt(7, id);

            int adminID = Integer.parseInt(adminIDText.getText());
            pstmt.setInt(8, adminID);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "insertion succesful");
            
            String sq="insert into patient_allergies values (?,?)";
            PreparedStatement ps = conn.prepareStatement(sq);
            ps.setInt(1, Integer.parseInt(fileNumText.getText()));
            ps.setString(2, allergyText.getText());
            ps.executeUpdate();
            
            conn.close();

            /* String type="";

            if(chooseP.isSelected())
            type = chooseP.getText();

            if(chooseD.isSelected())
            type= chooseD.getText();

            switch(type)  {

                case "Patient":

                break;

                case "Doctor":

                break;
            }   */

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        buttonGroup1.clearSelection();
        fileNumText.setText("");
        fNameText.setText("");
        LNameText.setText("");
        phoneNumText.setText("");
        specialtyText.setText("");
        DOSText.setText("");
        genderText.setText("");
        DOBText.setText("");
        adminIDText.setText("");
        emailText.setText("");
        depText.setText("");
        depText.setText("");
        allergyText.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic_management", "root", "Ghala_439202867");
            String sql = "insert into doctor values(?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            int docID = Integer.parseInt(IDText.getText());
            pstmt.setInt(1, docID);
            pstmt.setString(2,fNameText.getText());
            pstmt.setString(3,LNameText.getText());
            pstmt.setString(4,specialtyText.getText());
            pstmt.setString(5,emailText.getText());
            pstmt.setString(6,phoneNumText.getText());
            int dept = Integer.parseInt(depText.getText());
            pstmt.setInt(7, dept);

            long millis= System.currentTimeMillis();
            java.sql.Date date = new java.sql.Date(millis);
            date.valueOf(DOSText.getText());
            pstmt.setDate(8, date);

            int adminID = Integer.parseInt(adminIDText.getText());
            pstmt.setInt(9, adminID);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "insertion succesful");
            conn.close();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_add1ActionPerformed

    private void choosePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePActionPerformed
        // TODO add your handling code here:
        
            jPanel2.setEnabled(true);
            fileNumText.setEnabled(true);
            allergyText.setEnabled(true);
            DOBText.setEnabled(true);
            genderText.setEnabled(true);
            jPanel1.setEnabled(false);
            emailText.setEnabled(false);
            DOSText.setEnabled(false);
            specialtyText.setEnabled(false);
            depText.setEnabled(false);
        
    }//GEN-LAST:event_choosePActionPerformed

    private void chooseDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDActionPerformed
        // TODO add your handling code here:
            jPanel2.setEnabled(false);
            fileNumText.setEnabled(false);
            allergyText.setEnabled(false);
            DOBText.setEnabled(false);
            genderText.setEnabled(false);
            jPanel1.setEnabled(true);
            emailText.setEnabled(true);
            DOSText.setEnabled(true);
            specialtyText.setEnabled(true);
            depText.setEnabled(true);
    }//GEN-LAST:event_chooseDActionPerformed

    private void searchFileNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFileNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFileNumTextActionPerformed

    private void searchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPatientActionPerformed

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic_management", "root", "Ghala_439202867");

            String sql = "select * from patient where FileNum = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1,Integer.parseInt(searchFileNumText.getText()));

            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){

                searchPatientText.append(rs.getString("Fname"));
                searchPatientText.append(" ");
                searchPatientText.append(rs.getString("Lname"));
                searchPatientText.append("\n");
                searchPatientText.append(rs.getString("contactNum"));
                searchPatientText.append("\n");
                searchPatientText.append(rs.getString("gender"));
                searchPatientText.append("\n");
                searchPatientText.append(rs.getString("DateOfBirth"));
                searchPatientText.append("\n");
                searchPatientText.append(rs.getString("NationalID"));
                searchPatientText.append("\n");
                searchPatientText.append(rs.getString("admin_ID"));
                searchPatientText.append("\n______________________________________");

                

            }else{
                JOptionPane.showMessageDialog(null,"Record not found");
            }
            conn.close();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }

        // TOSEARCH FOR PATIENTS IN DIRECTORY:
    }//GEN-LAST:event_searchPatientActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        searchFileNumText.setText("");
        searchPatientText.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchDocIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDocIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDocIDTextActionPerformed

    private void searchDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDocActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic_management", "root", "Ghala_439202867");

            String sql = "select * from doctor where docID = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1,Integer.parseInt(searchDocIDText.getText()));

            ResultSet rs = pstmt.executeQuery();
            if(rs.next()){
                searchDocText.append(rs.getString("Fname"));
                searchDocText.append(" ");
                searchDocText.append(rs.getString("Lname"));
                searchDocText.append("\n");
                searchDocText.append(rs.getString("specialty"));
                searchDocText.append("\n");
                searchDocText.append(rs.getString("email"));
                searchDocText.append("\n");
                searchDocText.append(rs.getString("phoneNum"));
                searchDocText.append("\n");
                searchDocText.append(rs.getString("deptNum"));
                searchDocText.append("\n");
                searchDocText.append(rs.getString("DateOfStart"));
                searchDocText.append("\n");
                searchDocText.append(rs.getString("AdminID"));
                searchDocText.append("\n______________________________________");


            }else{
                JOptionPane.showMessageDialog(null,"Record not found");
            }

            conn.close();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }

        // TOSEARCH FOR DOCTORS IN DIRECTORY:
    }//GEN-LAST:event_searchDocActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        searchDocIDText.setText("");
        searchDocText.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void upcomingApp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcomingApp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upcomingApp2ActionPerformed

    private void allDoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allDoc2ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic_management", "root", "Ghala_439202867");

            String sql = "select * from doctor";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            //pstmt.setInt(1,searchDocIDText.getText());

            ResultSet rs = pstmt.executeQuery();
            while(rs.next()){
                viewText.append(rs.getString("Fname"));
                viewText.append(" ");
                viewText.append(rs.getString("Lname"));
                viewText.append("\n");
                viewText.append(rs.getString("specialty"));
                viewText.append("\n");
                viewText.append(rs.getString("email"));
                viewText.append("\n");
                viewText.append(rs.getString("phoneNum"));
                viewText.append("\n");
                viewText.append(rs.getString("deptNum"));
                viewText.append("\n");
                viewText.append(rs.getString("DateOfStart"));
                viewText.append("\n");
                viewText.append(rs.getString("AdminID"));
                viewText.append("\n______________");

            } 
//            else{
//                JOptionPane.showMessageDialog(null,"Record not found");
//            }

            conn.close();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_allDoc2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        viewText.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOBText;
    private javax.swing.JTextField DOSText;
    private javax.swing.JTextField IDText;
    private javax.swing.JLabel LName;
    private javax.swing.JTextField LNameText;
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JPanel addText;
    private javax.swing.JTextField adminIDText;
    private javax.swing.JButton allDoc;
    private javax.swing.JButton allDoc1;
    private javax.swing.JButton allDoc2;
    private javax.swing.JButton allPatient;
    private javax.swing.JButton allPatient1;
    private javax.swing.JButton allPatient2;
    private javax.swing.JTextField allergyText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chooseD;
    private javax.swing.JRadioButton chooseP;
    private javax.swing.JTextField depText;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel fName;
    private javax.swing.JTextField fNameText;
    private javax.swing.JTextField fileNumText;
    private javax.swing.JTextField genderText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField phoneNumText;
    private javax.swing.JButton searchDoc;
    private javax.swing.JTextField searchDocIDText;
    private javax.swing.JTextArea searchDocText;
    private javax.swing.JTextField searchFileNumText;
    private javax.swing.JButton searchPatient;
    private javax.swing.JTextArea searchPatientText;
    private javax.swing.JTextField specialtyText;
    private javax.swing.JButton upcomingApp;
    private javax.swing.JButton upcomingApp1;
    private javax.swing.JButton upcomingApp2;
    private javax.swing.JTextArea viewText;
    private javax.swing.JTextArea viewText1;
    private javax.swing.JTextArea viewText2;
    // End of variables declaration//GEN-END:variables
}
